version: 1.0.{build}.{branch}
branches:
  only:
  - master
image: Visual Studio 2022
configuration: Release
nuget:
  disable_publish_on_pr: false
before_build:
- cmd: nuget restore
build:
  project: '%project_name%\%project_name%.csproj'
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: .\OutputNuget\RFBCodeWorks.Mvvm.Dialogs*.nupkg